services:

  backend:
    build:
      context: .
    ports:
      - "9966:9966"
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exchange_rate_db

  db:
    image: postgres:16.9
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange_rate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql

  wiremock:
    image: wiremock/wiremock:3.13.1
    ports:
      - "9090:8080"
    volumes:
      - ./src/main/resources/wiremock/mappings:/home/wiremock/mappings
