create table exchange_rates(
    currency_pair varchar(255) not null primary key,
    rate          numeric(38, 2)
);

create table exchange_rate_transactions(
    id bigint generated by default as identity primary key,
    amount           numeric(38, 2),
    converted_amount numeric(38, 2),
    exchange_rate    numeric(38, 2),
    from_currency    varchar(255),
    to_currency      varchar(255),
    transaction_date timestamp(6)
);